export const authConstants = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  //---------------
  USER_REGISTRATION: 'USER_REGISTRATION',
  USER_REGISTRATION_ERROR: 'USER_REGISTRATION_ERROR',
  USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
  //---------------
  USER_REFRESH_TOKEN: 'USER_REFRESH_TOKEN',
  USER_REFRESH_TOKEN_ERROR: 'USER_REFRESH_TOKEN_ERROR',
  USER_REFRESH_TOKEN_SUCCESS: 'USER_REFRESH_TOKEN_SUCCESS',
  //---------------
  SIGNUP_NAME_CHANGE: 'SIGNUP_NAME_CHANGE',
  SIGNUP_EMAIL_CHANGE: 'SIGNUP_EMAIL_CHANGE',
  SIGNUP_NUMBER_CHANGE: 'SIGNUP_NUMBER_CHANGE',
  SIGNUP_PASSWORD_CHANGE: 'SIGNUP_PASSWORD_CHANGE',
  SIGNUP_PASSWORD_REPEAT_CHANGE: 'SIGNUP_PASSWORD_REPEAT_CHANGE',
  //-------
  SIGNUP_FORM_CHANGE: 'SIGNUP_FORM_CHANGE',
  SIGNUP_FORM_CORRECT: 'SIGNUP_FORM_CORRECT',
  SIGNUP_FORM_ERROR: 'SIGNUP_FORM_ERROR',
  //------
  LOGIN_FORM_CHANGE: 'LOGIN_FORM_CHANGE',
  LOGIN_FORM_CORRECT: 'LOGIN_FORM_CORRECT',
  LOGIN_FORM_ERROR: 'LOGIN_FORM_ERROR',
  //-----
  RESET_FORM: 'RESET_FORM',
};
