export const categoryConstants = {
  //----- GET
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_SINGLE_CATEGORY: 'GET_SINGLE_CATEGORY',
  //----- POST
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
};
