export const productConstants = {
  //----- GET
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  //--------------------------------
  GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
  GET_SINGLE_PRODUCT_ERROR: 'GET_SINGLE_PRODUCT_ERROR',
  GET_SINGLE_PRODUCT_SUCCES: 'GET_SINGLE_PRODUCT_SUCCESS',
  //--------------------------------
  GET_PRODUCTS_PAGINATION: 'GET_PRODUCTS_PAGINATION',
  GET_PRODUCTS_PAGINATION_ERROR: 'GET_PRODUCTS_PAGINATION_ERROR',
  GET_PRODUCTS_PAGINATION_SUCCESS: 'GET_PRODUCTS_PAGINATION_SUCCESS',
  //----- POST
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
  CREATE_PRODUCT_SUCCES: 'CREATE_PRODUCT_SUCCESS',
  //--------------------------------
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
  DELETE_PRODUCT_SUCCES: 'DELETE_PRODUCT_SUCCES',
};
