export default {
  CABINET_SCREEN: 'cabinetScreen',
  HOME_SCREEN: 'homeScreen',
  THEME_TOGGLER: 'themeToggle',
  CART_SCREEN: 'CART_SCREEN',
  REGISTRATION_SCREEN: 'REGISTRATION_SCREEN',
  REGISTRATION_FORM: 'REGISTRATION_FORM',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
};
